### ISSUE TITLE
VCF incorrectly specifies phased genotypes

### ISSUE THREAD

**Issue by davidlougheed** [gymrek-lab/LongTR#11]
Hello,
I ran LongTR on some data, specifying a `.vcf.gz` file as output, but ran into the following issue with said output:

* ~~the contents of the file are a plain-text VCF, not a bgzipped VCF, despite it ending with the `.vcf.gz` suffix~~
* the genotypes are separated by a `|`, not `/`, which indicates phased genotypes, but I did not provide a SNP VCF for it to phase with (the BAM is technically phased though, so maybe it's automatically using those haplotags? but I'm pretty sure it isn't.)

**Comment by davidlougheed** [comment]
Ah my apologies, I got confused; my editor was automatically decompressing them on the fly - I'm very sorry. I'll re-title the issue to just refer to the phasing for future reference for others.

**Comment by heliziii** [comment]
No worries!
