### ISSUE TITLE
segfault when using --skip-assembly on pacbio HG002 bam

### ISSUE THREAD

**Issue by bw2** [gymrek-lab/LongTR#14]
I'm having trouble running 
```
LongTR --skip-assembly --bams HG002.subset.bam  --fasta Homo_sapiens_assembly38.fasta --regions repeats.bed --log out.log --tr-vcf out.vcf.gz
```
on these files:
https://www.dropbox.com/scl/fi/ik6umjhkjujwjlpnp0ia4/files.zip?rlkey=nfl6lg4a4g9jgzjryxqs4t897&st=v4cccuat&dl=0

but don't see an obvious reason:

<img width="1638" alt="image" src="https://github.com/gymrek-lab/LongTR/assets/6240170/88680778-1c2f-4cc2-97a7-29ffc85f9908">

It completed successfully on another pacbio bam from a different source.

**Comment by heliziii** [comment]
Hello,

We made the skip-assembly tag as default as it was causing so much confusion, please remove it from your tags. I have updated the document, I apologize for the inconvenience.

Best,
Helia

**Comment by bw2** [comment]
Will do, thanks.
