### ISSUE TITLE
Where do I find the per-allele support?

### ISSUE THREAD

**Issue by wdecoster** [gymrek-lab/LongTR#16]
Hi,

I found the DP value, but how can I get the per allele number of supporting reads?

Best,
Wouter

**Comment by heliziii** [comment]
Hi,

For each sample there are two FORMAT fields that should help with that, ALLREADS and MALLREADS. ALLREADS shows number of supporting reads per raw differences, and MALLREADS shows number of supporting reads for each of the maximum likelihood alleles in a heterozygous call. For example, lets say FORMAT looks like this:

GT:GB:Q:PQ:DP:DSNP:DFLANKINDEL:PDP:PSNP:GLDIFF:ALLREADS:MALLREADS	1|2:0|77:1.00:0.50:3:0:0:0|0:0|0:9.47:0|1;77|1;78|1:0|1;77|2

where ALLREADS is 0|1;77|1;78|1, and it shows that among 3 overlapping **raw** reads, one had REF length, one had a 77bp insertion and one had a 78bp insertion. 

Then MALLREADS is 0|1;77|2, which means after maximum likelihood genotyping, one read was assigned to the allele with the REF length and two reads were assigned to the allele with 77bp insertion.

Let me know if you have any other question.

Best,
Helia
