### ISSUE TITLE
LongTR v1.1 segfaults after "Processing flanking sequences"

### ISSUE THREAD

**Issue by davidlougheed** [gymrek-lab/LongTR#19]
Hello,
When I run the latest LongTR v1.1, I get an exit code 11 (segfault) almost immediately after calling begins, right after `Processing flanking sequences`:

```
...
Processing region chr1 16710 16743
29 reads overlapped region, of which 
	0 were hard clipped
	0 had an 'N' base call
	6 had low MAPQ
	1 had low base quality scores
	0 did not span the STR
	0 did not have a unique mapping
	22 PASSED ALL FILTERS
Phased SNPs add info for 0 out of 22 reads and 0 out of 1 samples
Trimming reads
Generating candidate haplotypes
	GTGGGAGTGGGGGTGCACTGGCCAGCACCTCAGGA GCTGGGGGTGGTGGTGGGGGCGGTGGGGGTGGT GTTAGTACCCCATCTTGTAGGTCTGAAACACAAAG 
Added 0 inexact haplotypes generated by POA
Aligning reads to each candidate haplotype
Processing flanking sequences
```

At which point the job exits with code 11 indicating a segmentation fault. This did not happen in version 1.0.

**Comment by heliziii** [comment]
Hi David,

Do you have --skip-assembly in your list of parameters? If so, please remove it, I decided to remove this option as it was causing so much confusion. Otherwise, please share your script so I can look further.

Thanks,
Helia

**Comment by davidlougheed** [comment]
ah yes, that is in my list of parameters, I did not realize the parameters had changed. I'll try running it without.
