### ISSUE TITLE
Low base quality score for ONTs data

### ISSUE THREAD

**Issue by quantrannnn** [gymrek-lab/LongTR#4]
Hello, 
I tried running LongTR for my ONT datas but the output filters out most of my reads because of the low base quality score:
181 reads overlapped region, of which:
	5 were hard clipped
	0 had an 'N' base call
	176 had low base quality scores
	0 did not have a unique mapping
	0 PASSED ALL FILTERS
I alreadly set --min-sum-qual to 0 or 7. This dataset worked with STraglr and TRGT. Could you help me?
Thanks,

**Comment by heliziii** [comment]
Hello,

Thank you for using LongTR! Can you please pull and install the latest version? --min-sum-qual is now changed to --min-mean-qual with the default value of 30, showing the average quality score over the sequence. 

Please let me know if you have any other questions.

Best,
Helia

**Comment by quantrannnn** [comment]
Hi Helia,

Thank you!  I installed the latest version and it works well now.

Best,

**Comment by heliziii** [comment]
Great!
