### ISSUE TITLE
TR region BED file - are start coordinates 1-based or 0-based?

### ISSUE THREAD

**Issue by bw2** [gymrek-lab/LongTR#5]
Would be nice to clarify this @  https://github.com/gymrek-lab/LongTR?tab=readme-ov-file#tr-region-bed-file
```
2. The start position of the TR on its chromosome
```

**Comment by heliziii** [comment]
Hi Ben,

Start coordinates should be 1-based. I will add this to the documentation. Thank you!

Best,
Helia

**Comment by davidlougheed** [comment]
Hello,
It's worth noting that the official BED specification requires 0-based, half-open coordinates: https://github.com/samtools/hts-specs/blob/master/BEDv1.pdf
