### ISSUE TITLE
Issue Cloning LongTR Repository: Permission Denied

### ISSUE THREAD

**Issue by isrbbc** [gymrek-lab/LongTR#9]
Hello,

I am having trouble cloning the LongTR repository on GitHub. When I run git clone git@github.com:gymrek-lab/LongTR.git, I keep getting this error:

Cloning into 'LongTR'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

I haven't been able to get past it. Any help on this would be awesome. Thanks a ton!

Cheers,
Indhu

**Comment by heliziii** [comment]
Hello,

This issue is because GitHub is not able to authorize you. please follow the instructions here:

https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey

Best,
Helia

**Comment by isrbbc** [comment]
Thank you!
